services:
  nginx:
    image: nginx:alpine
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./public:/app:ro"
    ports:
      - "8080:80"
  
  php:
    image: php:fpm-alpine
    volumes:
      - "./public:/app:ro"
