x-build: &build
  context: src
  dockerfile: docker/Dockerfile

services:
  nginx:
    build:
      <<: *build
      target: nginx
    ports: 
      - "8080:80"
  
  php:
    build:
      <<: *build
      target: php
